# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
# TODO: use the newer Gateway API instead of a IngressRoute resource
# https://doc.traefik.io/traefik/routing/providers/kubernetes-gateway/
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: >-
        Host(`{{.Values.ingress.hostname}}`) &&
        (Path(`/committees`) || PathPrefix(`/committees`))
      priority: 10
      middlewares:
        {{- if .Values.heimdall.enabled }}
        - name: heimdall
        {{- end }}
      services:
        - kind: Service
          name: {{ .Chart.Name }}
          port: web